frontpage:
    path: /
    defaults:  { _controller: MyApp\Controller\AppController::frontpageAction }

assets:
    path: "/.{postfix}"
    requirements:
        postfix: .+

# Example

account_view:
    path: /{accountName}
    defaults:  { _controller: Radvance\Controller\AccountController::viewAction }

space_view:
    path: /{accountName}/{spaceName}
    defaults:  { _controller: Radvance\Controller\SpaceController::viewAction }

space_add:
    path: /{accountName}/addSpace
    defaults:  { _controller: Radvance\Controller\SpaceController::addAction }
