frontpage:
    path: /
    defaults:  { _controller: BlogApp\Controller\AppController::frontpageAction }

assets:
    path: "/.{postfix}"
    requirements:
        postfix: .+

# Example

example_index:
    path: /{accountName}
    defaults:  { _controller: ExampleApp\Controller\ExampleController::indexAction }

example_view:
    path: /{accountName}/{exampleName}
    defaults:  { _controller: ExampleApp\Controller\ExampleController::viewAction }

example_add:
    path: /{accountName}/addExample
