# Meta routes

meta_robot:
    pattern: /robots.txt
    defaults: { _controller: Radvance\Controller\MetaController::robotAction }
meta_favicon:
    pattern: /favicon.ico
    defaults: { _controller: Radvance\Controller\MetaController::faviconAction }
