# Permission routes

permission_index:
    path: /{accountName}/{spaceName}/permissions
    defaults: { _controller: Radvance\Controller\PermissionController::indexAction }
permission_add:
    path: /{accountName}/{spaceName}/permissions/add
    defaults: { _controller: Radvance\Controller\PermissionController::addAction }
    requirements: { _method: post }
permission_delete:
    path: /{accountName}/{spaceName}/permissions/{permissionId}/delete
    defaults: { _controller: Radvance\Controller\PermissionController::deleteAction }
