# dashboard

dashboard:
    pattern: /dashboard
    defaults: { _controller: Radvance\Controller\DashboardController::indexAction }

# library routes

space_index:
    pattern: /{accountName}
    defaults: { _controller: Radvance\Controller\SpaceController::indexAction }
space_add:
    pattern: /{accountName}/addlibrary
    defaults: { _controller: Radvance\Controller\SpaceController::addAction }
space_view:
    pattern: /{accountName}/{spaceName}
    defaults: { _controller: Radvance\Controller\SpaceController::viewAction }
space_edit:
    pattern: /{accountName}/{spaceName}/edit
    defaults: { _controller: Radvance\Controller\SpaceController::editAction }
space_delete:
    pattern: /{accountName}/{spaceName}/delete
    defaults: { _controller: Radvance\Controller\SpaceController::deleteAction }

# Permission routes

permission_index:
    pattern: /{accountName}/{spaceName}/permissions
    defaults: { _controller: Radvance\Controller\PermissionController::indexAction }
permission_add:
    pattern: /{accountName}/{spaceName}/permissions/add
    defaults: { _controller: Radvance\Controller\PermissionController::addAction }
    requirements: { _method: post }
permission_delete:
    pattern: /{accountName}/{spaceName}/permissions/{permissionId}/delete
    defaults: { _controller: Radvance\Controller\PermissionController::deleteAction }
