# dashboard

dashboard:
    path: /dashboard
    defaults: { _controller: Radvance\Controller\DashboardController::indexAction }

# space routes

space_new:
    path: /new
    defaults: { _controller: Radvance\Controller\SpaceController::newAction }

space_index:
    path: /{accountName}
    defaults: { _controller: Radvance\Controller\SpaceController::indexAction }
space_add:
    path: /{accountName}/addlibrary
    defaults: { _controller: Radvance\Controller\SpaceController::addAction }
space_view:
    path: /{accountName}/{spaceName}
    defaults: { _controller: Radvance\Controller\SpaceController::viewAction }
space_edit:
    path: /{accountName}/{spaceName}/edit
    defaults: { _controller: Radvance\Controller\SpaceController::editAction }
space_delete:
    path: /{accountName}/{spaceName}/delete
    defaults: { _controller: Radvance\Controller\SpaceController::deleteAction }
